### ISSUE TITLE
[WIKI] Looking for help at wiki,

### ISSUE THREAD

**Issue by TheKillerTacos** [TKRT-Creations/SkyBlockPVP#5]
So the title says it

**Comment by Skyladd** [comment]
okay id like to help, should i research how to make one? Orrr, im kind of a noob with github xD tell me what you need

**Comment by Skyladd** [comment]
I can make minimalistic artwork and write stuff xD

**Comment by TheKillerTacos** [comment]
Just the simple stuff, Make the pages, then at the Home/first page make it look like wiki? 
and then make another page with Permissions, i will give it to you in a list here, and commands, which i also will give, that for the moment,

**Comment by TheKillerTacos** [comment]
and also ill make a Examples.md, so you can get based on some stuff

**Comment by Skyladd** [comment]
Okay do i need to be listed as a contributer? Ive honestly never made a page on github but id love to

**Comment by TheKillerTacos** [comment]
yea, wait im going to add you...

**Comment by Skyladd** [comment]
thanks

**Comment by TheKillerTacos** [comment]
ok, now you are a contributor..

**Comment by Skyladd** [comment]
okay ill see what i can do

**Comment by Skyladd** [comment]
What kind of artwork would you like?

**Comment by TheKillerTacos** [comment]
Just a Island like the one:
http://img03.deviantart.net/db53/i/2012/144/9/a/sky_block_by_biodrawxel-d50ynd0.png

**Comment by Skyladd** [comment]
Hey should include the server working for 0.13? The full 0.14 release is out now--just asking

**Comment by TheKillerTacos** [comment]
yea it works from since the API 1.13, but after PHP7 support, it will be only for 0.14.0,

**Comment by TheKillerTacos** [comment]
im going to rewrite the code, it seem really outdated,

**Comment by Skyladd** [comment]
Alright im trying to make the wiki as stylish as possible lol. Ive made some changes but im going to start adding commands and permissions pages, are they ready?

**Comment by TheKillerTacos** [comment]
ill list them here:
sbpvp - main permission
sbpvp.is - /is main command permission (user)
sbpvp.is.help - /is help command permission (user)
sbpvp.is.create - /is create to create island permission (user)
sbpvp.is.delete - /is delete to delete island permission (user)
sbpvp.is.get - Gets a players island location (OP)
sbpvp.is.get.tp - TP to a players island (OP)

ill add more, brb,

**Comment by Skyladd** [comment]
sbpvp? Why pvp lol xD ill add them

**Comment by TheKillerTacos** [comment]
going to make the plugin like, Skyblock With Kitpvp SkyblockPVP

**Comment by Skyladd** [comment]
im kinda confused. you can explain it later lol. ill start adding stuff

**Comment by TheKillerTacos** [comment]
adding arenas, nether worlds are Fully PVP, leveling up unlocks kits (future update hoping 1.8A)
and a implemention of economies plugins.

**Comment by TheKillerTacos** [comment]
ill do so, brb,

**Comment by Skyladd** [comment]
oh, the server i have for pe is Genisys, they have nether but its kinda buggy. will kits be tied in with essentialspe? Its all so confusing :D but so cool

**Comment by TheKillerTacos** [comment]
yea it will, or make a KitAPI within skyblock, which will be triggable (on/off/auto if gets conflicts with other kits plugins) and i use ClearSky, but hope Nether gets fixed on mostly all PM Core servers

**Comment by TheKillerTacos** [comment]
ok ill be back in a hour or less.

**Comment by Skyladd** [comment]
Can i replace the "actual" with Plugin Version ?

**Comment by TheKillerTacos** [comment]
closing it!
